"""run metrics and pose errors

Revision ID: 723726176e7a
Revises: fd49165b2088
Create Date: 2026-08-10 23:40:38.520191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '723726176e7a'
down_revision: Union[str, Sequence[str], None] = 'fd49165b2088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pose_errors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('timestamp_ns', sa.BigInteger(), nullable=False),
    sa.Column('trans_error', sa.Float(), nullable=False),
    sa.Column('rot_error', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pose_errors_run_ts', 'pose_errors', ['run_id', 'timestamp_ns'], unique=False)
    op.create_table('run_metrics',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('ate_rmse', sa.Float(), nullable=False),
    sa.Column('ate_mean', sa.Float(), nullable=False),
    sa.Column('ate_median', sa.Float(), nullable=False),
    sa.Column('ate_max', sa.Float(), nullable=False),
    sa.Column('ate_rot_rmse', sa.Float(), nullable=False),
    sa.Column('ate_rot_std', sa.Float(), nullable=False),
    sa.Column('rpe_trans_rmse', sa.Float(), nullable=True),
    sa.Column('rpe_rot_rmse', sa.Float(), nullable=True),
    sa.Column('rpe_delta_frames', sa.Integer(), nullable=False),
    sa.Column('scale_error', sa.Float(), nullable=True),
    sa.Column('alignment', sa.String(length=8), nullable=False),
    sa.Column('aligned_pose_count', sa.Integer(), nullable=False),
    sa.Column('candidate_pose_count', sa.Integer(), nullable=False),
    sa.Column('association_tolerance_ns', sa.BigInteger(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_metrics')
    op.drop_index('ix_pose_errors_run_ts', table_name='pose_errors')
    op.drop_table('pose_errors')
    # ### end Alembic commands ###
