"""runs and poses

Revision ID: fd49165b2088
Revises: 5c89867cc212
Create Date: 2026-08-10 19:54:52.355983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd49165b2088'
down_revision: Union[str, Sequence[str], None] = '5c89867cc212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('failure_frame', sa.Integer(), nullable=True),
    sa.Column('processed_frames', sa.Integer(), nullable=False),
    sa.Column('total_frames', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_runs_dataset_created', 'runs', ['dataset_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('poses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=False),
    sa.Column('timestamp_ns', sa.BigInteger(), nullable=False),
    sa.Column('tx', sa.Float(), nullable=False),
    sa.Column('ty', sa.Float(), nullable=False),
    sa.Column('tz', sa.Float(), nullable=False),
    sa.Column('qw', sa.Float(), nullable=False),
    sa.Column('qx', sa.Float(), nullable=False),
    sa.Column('qy', sa.Float(), nullable=False),
    sa.Column('qz', sa.Float(), nullable=False),
    sa.Column('tracked_features', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_poses_run_ts', 'poses', ['run_id', 'timestamp_ns'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_poses_run_ts', table_name='poses')
    op.drop_table('poses')
    op.drop_index('ix_runs_dataset_created', table_name='runs')
    op.drop_table('runs')
    # ### end Alembic commands ###
